sudo: required
language: node_js

services:
  - docker

before_install:
  - docker build -t zl/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true zl/react-test npm test

after_success:
  - docker build -t abbottqwq/multi-client ./client
  - docker build -t abbottqwq/multi-nginx ./nginx
  - docker build -t abbottqwq/multi-server ./server
  - docker build -t abbottqwq/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push abbottqwq/multi-client
  - docker push abbottqwq/multi-nginx
  - docker push abbottqwq/multi-server
  - docker push abbottqwq/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: Multidocker-env
  bucket_name: elasticbeanstalk-us-east-2-204103620814
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY